<?php
/**
 * Desc: 企业当日额度明细
 * User: wwb
 * Date: 2017/10/9 0009
 * Time: 10:03
 */


class LogisticsDailyQuotaLogController extends WebAPIController
{
    public function pageInit()
    {
        parent::pageInit(); // TODO: Change the autogenerated stub
        $this->rightCode = 'logisticsDailyQuotaLog';
    }


}

