<?php
/**
 * Desc: 企业可用额度明细
 * User: wwb
 * Date: 2017/10/9 0009
 * Time: 10:03
 */


class LogisticsQuotaLogController extends WebAPIController
{
    public function pageInit()
    {
        parent::pageInit(); // TODO: Change the autogenerated stub
        $this->rightCode = 'logisticsQuotaLog';
    }


}

