<?php

/**
 * Desc: 物流企业
 * User: wwb
 * Date: 2017/10/9 0009
 * Time: 10:03
 */

class LogisticsCompanyController extends WebAPIController
{
    public function pageInit()
    {
        parent::pageInit(); // TODO: Change the autogenerated stub
        $this->rightCode = 'logistics';
    }

    /**
     * @api {POST} /webAPI/logisticsCompany/list [list]物流企业列表
     * @apiName list
     * @apiGroup WebAPI - logisticsCompany
     * @apiVersion 1.0.0
     * @apiParam (输入字段) {string} search 查询字段，<font color=red>非必填</font>
     * @apiParam (输入字段) {int} page 页数 <font color=red>非必填</font>
     * @apiParam (输入字段) {int} pageSize 分页大小 <font color=red>非必填</font>
     * @apiExample {json} 输入示例:
     * {
     * "page":2,
     * "pageSize":15,
     * "search"{
     *      "name":'广州凯中石油化工有限公司',
     *      "out_status":'2',
     *      "status":'1',
     *      }
     * }
     * @apiSuccessExample {json} 输出示例:
     *{
     *"state": 0,
     *"data": {
     *      "pageSize": 10,
     *      "totalPages": 1,
     *      "page": "1",
     *      "totalRows": "1",
     *      "data": [{
     *               "logistics_id": "1392",
     *               "out_status_name": "禁用",
     *               "name": "朝阳物流有限公司",
     *               "status_name": "正常",
     *               "is_can_edit": false,
     *               "is_can_view": false,
     *          }],
     *}
     * @apiParam (输出字段) {string} state 状态码
     * @apiParam (输出字段) {array} data 数据信息
     * @apiParam (输出字段-data) {array} data 列表数据
     * @apiParam (输出字段-data) {int} totalPages 列表总页数
     * @apiParam (输出字段-data) {int} totalRows 列表总记录数
     * @apiParam (输出字段-data) {int} page 当前页数
     * @apiParam (输出字段-data) {int} pageSize 每页显示记录数
     * @apiParam (输出字段-data) {array} rows 列表行数据信息
     * @apiParam (输出字段-data-data) {int} logistics_id 编号
     * @apiParam (输出字段-data-data) {string} name 企业名称
     * @apiParam (输出字段-data-data) {string} out_status_name 银管家状态
     * @apiParam (输出字段-data-data) {string} status_name 企业状态
     * @apiParam (输出字段-data-data) {string} is_can_edit 是否可修改
     * @apiParam (输出字段-data-data) {string} is_can_view 是否可查看
     */
	public function actionList()
	{
        $search = $this->getSearch();
        $attr = array(
            'a.name*'=>$search['name'],
            'a.out_status'=>$search['out_status'],
            'a.status'=>$search['status']
        );

        $where = $this->getWhereSql($attr);

        $sql = "SELECT  {col}
                FROM t_logistics_company a
                ".$where." ORDER BY logistics_id DESC";

        $fields = 'a.logistics_id,a.out_status,a.status,a.name';

        $data = $this->getPageData($sql, $fields);

        if(Utility::isEmpty($data->data)){
            $this->returnSuccess([]);
        }


        foreach($data->data as & $datum){
            $datum['out_status_name'] = Map::getStatusName('logistics_company_out_status', $datum['out_status']);
            $datum['status_name'] = Map::getStatusName('logistics_company_status', $datum['status']);
            $datum['is_can_view'] = true;
            $datum['is_can_edit'] = true;

        }

        $this->returnSuccess($data);
	}
    /**
     * @api {GET} /webAPI/logisticsCompany/detail [detail]物流企业详情
     * @apiName detail
     * @apiGroup WebAPI - logisticsCompany
     * @apiVersion 1.0.0
     * @apiParam (输入字段) {int} logistics_id 物流企业id <font color=red>必填</font>
     * @apiExample {json} 输入示例:
     * {
     * "logistics_id":2,
     * }
     * @apiSuccessExample {json} 输出示例:
     *{
     *"state": 0,
     *"data": {
     *      "search": null,
     *      "data": {
     *         "logistics_id": "1392",
     *         "out_status_name": "禁用",
     *         "name": "朝阳物流有限公司",
     *         "status_name": "正常",
     *         "status": "1",
     *         "is_can_edit": false,
     *      }
     *}
     * @apiParam (输出字段) {string} state 状态码
     * @apiParam (输出字段) {array} data 数据信息
     * @apiParam (输出字段-data) {id} logistics_id 编号
     * @apiParam (输出字段-data) {string} out_status_name 银管家状态
     * @apiParam (输出字段-data) {string} name 物流企业名称
     * @apiParam (输出字段-data) {string} status_name 企业状态
     * @apiParam (输出字段-data) {string} status 企业状态值
     * @apiParam (输出字段-data) {string} is_can_edit 是否可修改
     */
    public function actionDetail()
    {
        $id = Mod::app()->request->getParam('logistics_id');
        if (!Utility::checkQueryId($id)) {
            $this->returnError(RetailError::$PARAMS_PASS_ERROR);
        }

        //物流企业
        try{

        $service = new \app\ddd\Logistics\Application\LogisticsCompany\LogisticsCompanyService();
        $logisticsCompany = $service->getLogisticsCompany($id);
        if(empty($logisticsCompany))
            $this->returnError(BusinessError::outputError(\RetailError::$LOGISTICS_COMPANY_NOT_EXIST,array('logistics_id'=>$id)));

        $this->returnSuccess($logisticsCompany);

        }catch(Exception $e){
        $this->returnError(BusinessError::outputError(\RetailError::$OPERATE_FAILED, array('reason' => $e->getMessage())));
        }
    }
    /**
     * @api {POST} /webAPI/logisticsCompany/save [save]物流企业修改保存
     * @apiName save
     * @apiGroup WebAPI - logisticsCompany
     * @apiVersion 1.0.0
     * @apiParam  (输入字段){int} logistics_id 物流企业id <font color=red>必填</font>
     * @apiParam  (输入字段){int} status 企业状态 <font color=red>必填</font>
     * @apiExample {json} 输入示例:
     * {
     * "logistics_id":2,
     * "status":"1"
     * }
     * @apiSuccessExample {json} 输出示例:
     * 接收成功返回：
     * {
     *      "state":0,
     *      "data":"成功信息"
     * }
     * 失败返回：
     * {
     *      "state":1,
     *      "data": "错误信息"
     * }
     * @apiParam (输出字段) {string} state 错误码
     * @apiParam (输出字段) {array} data 操作信息
     */
    public function actionSave()
    {
        $logistics_id = $this->getRestParam('logistics_id');
        $status = $this->getRestParam('status');
        $params = array(
            'logistics_id'=>$logistics_id,
            'status'=>$status
        );
        if(empty($logistics_id)||!in_array($status,array('0','1')))
            $this->returnError(BusinessError::outputError(\RetailError::$PARAMS_PASS_ERROR));

        try{

            $servive = new \app\ddd\Logistics\Application\LogisticsCompany\LogisticsCompanyService();
            $servive->updateStatus($logistics_id,$status);

            $this->returnSuccess();

        }catch(Exception $e){
            $this->returnError(BusinessError::outputError(\RetailError::$OPERATE_FAILED, array('reason' => $e->getMessage())));
        }
    }
}

