<?php

/**
 * Desc: 测试接口
 * User: wwb
 * Date: 2017/10/9 0009
 * Time: 10:03
 */


class TestController extends WebAPIController
{
    public function pageInit() {
        parent::pageInit(); // TODO: Change the autogenerated stub
        $this->publicActions = ["stationPrice"];
    }

    public function actionStationPrice()
    {
        $stationId = Mod::app()->request->getParam('stationId');
        if (!Utility::checkQueryId($stationId))
        {
            $this->returnError(RetailError::$PARAMS_PASS_ERROR);
        }

        try
        {
            $data = \ddd\Infrastructure\DIService::get(\ddd\Order\Application\GoodsService::class)->getOilStationAllCanSellGoods($stationId);
            $this->returnSuccess($data);
        } catch (Exception $e)
        {
            $this->returnError($e->getMessage());
        }
    }
}

